Update BR.md
slghtr-says/servercert pull request #1
Opened 2023-11-21 17:15 UTC by slghtr-says

Proposal: Modify section 3.2.2.4.7 to allow CNAME delegation to the CA

Discussion on the proposal can be found here: https://docs.google.com/document/d/1_Shdqcj9TzMl7a_ULJ3ACJrhzYxGUB-7BVG3hv8gey4/edit?usp=sharing

2023-11-30 16:26 UTC, dzacharo requested changes
Proposed changes.

2023-11-30 16:26 UTC, dzacharo commented on docs/BR.md
> +CAs MAY operate domains for the purpose of assisting customers with this validation, and MAY instruct customers to add a CNAME redirect from an Authorization Domain Name to such a domain. If the CA d
```suggestion
CAs MAY operate Domain Names for the purpose of assisting Applicants with this validation, and MAY instruct Applicants to add a CNAME record from an Authorization Domain Name to such a Domain Name operated by the CA. If the CA does so, the CA SHALL 
```

2023-11-30 16:26 UTC, dzacharo commented on docs/BR.md
> +  i. ensure that each domain name is used for a unique Applicant, and not shared across multiple Applicants; and
```suggestion
  i. ensure that each Domain Name operated by the CA is used for a unique Applicant, and not shared across multiple Applicants; and 
```

2024-02-05 16:50 UTC, slghtr-says commented on docs/BR.md
> +  ii. complete the validation within the TTL of the CNAME record, or 8 hours, whichever is lesser; and
```suggestion
  ii. complete the validation within 8 hours.; and
```
The previous language attempts to set a maximum bound on the time the CA can rely on the results of DNS lookup for the purposes of domain validation. Setting the lower bound to the TTL however does not account for practically invalid scenarios such as a TTL of 0 or  less than 30 seconds. Well operated CAs may not be able to meet such strict time constraints. To simplify the constraint, I suggest removing the mention of TTLs and setting the upper bound for the usage of the DNS query results to 8 hours.

2024-02-07 12:02 UTC, XolphinMartijn commented on docs/BR.md
> +Confirming the Applicant's control over the FQDN by confirming the presence of a Random Value or Request Token for either in a DNS CNAME, TXT or CAA record for 1) an Authorization Domain Name; or 2)
```suggestion
Confirming the Applicant's control over the FQDN by confirming the presence of a Random Value or Request Token either in a DNS CNAME, TXT or CAA record for 1) an Authorization Domain Name; or 2) an Authorization Domain Name that is prefixed with a Domain Label that begins with an underscore character; or 3) a Prefixed Canonical Authorization Domain Name.
```

2024-02-07 12:06 UTC, XolphinMartijn commented on docs/BR.md
> +  i. ensure that each Prefixed Canonical Authorization Domain Name is used for a unique Applicant, and not shared across multiple Applicants; and
Should this say Applicant, or Account?
There's a meaningful difference between Applicant-binding, and Account-binding. I've been under the assumption that we're going to perform Account-binding for this

2024-02-07 12:08 UTC, XolphinMartijn commented on docs/BR.md
> +CAs MAY operate domains for the purpose of assisting Applicants with this validation, and MAY instruct Applicants to add a CNAME record containing a Prefixed Canonical Authorization Domain Name. If t
Is it clear that this overrules the time and reuse constraints that are put on Random Value and Request Token values? 

Also should this state "containing a Prefixed Canonical Authorization Domain Name **pointing to a CA-owned domain name**"?

2024-02-07 12:10 UTC, XolphinMartijn commented on docs/BR.md
> +  ii. complete the validation within the TTL of the CNAME record, or 8 hours, whichever is lesser; and
I worry that 8 hours by default is too much. If the record points towards the CA, the CA could easily re-check if a certain amount of time has expired. Maybe we should limit this down to an hour, otherwise the CA needs to re-check if the record still exists?

2024-02-07 12:11 UTC, XolphinMartijn commented on docs/BR.md
> +  iii. restrict the DNS record types in the CA operated DNS zone to those required for confirming the Applicant’s control over the FQDN.
I'm trying to find the meaning being. This does show that, for the purpose of delegating DCV to the CA, the CA must use a different domain name, for which no other records are hosted in the DNS zone?

2024-02-08 17:03 UTC, wthayer commented on docs/BR.md
> +
That's good, but this should be clarified since it can be read as either:

"The domain [contained within the RDATA value of a CNAME record from an Authorization Domain Name that is prefixed with a Domain Label that begins with an underscore character]"
or:
"[The domain that is prefixed with a Domain Label that begins with an underscore character] that is contained within the RDATA value of a CNAME record from an Authorization Domain Name"

2024-02-13 15:25 UTC, slghtr-says commented on docs/BR.md
> +  i. ensure that each Prefixed Canonical Authorization Domain Name is used for a unique Applicant, and not shared across multiple Applicants; and
The mitigation we landed on in the Threat-Model was "Applicant Unique CNAMEs". That said, we may have used the terms applicant and account interchangeably at times. 

The reasons I'm in favor of Applicant is 1) the noun "Account" is not defined or used in the BR's today and 2) if we were to define it, I imagine it would be similar to how "Applicant" is defined. 

> Applicant: The natural person or Legal Entity that applies for (or seeks renewal of) a Certificate.
Once the Certificate is issued, the Applicant is referred to as the Subscriber. For Certificates issued to
devices, the Applicant is the entity that controls or operates the device named in the Certificate, even
if the device is sending the actual certificate request

Based on that definition, I believe ensuring that the CA is generating unique PeCAns (Prefixed Canonical Authorization Domain Names) for each Applicant achieves the desired outcome. 

Does that make sense?

2024-02-13 15:33 UTC, slghtr-says commented on docs/BR.md
> +CAs MAY operate domains for the purpose of assisting Applicants with this validation, and MAY instruct Applicants to add a CNAME record containing a Prefixed Canonical Authorization Domain Name. If t
Does this make it any clearer?
```suggestion
CAs MAY operate domains for the purpose of assisting Applicants with this validation, and MAY instruct Applicants to add a CNAME record containing a Prefixed Canonical Authorization Domain Name operated by the CA. If the CA does so, the CA SHALL 
```

2024-02-13 15:36 UTC, XolphinMartijn commented on docs/BR.md
> +CAs MAY operate domains for the purpose of assisting Applicants with this validation, and MAY instruct Applicants to add a CNAME record containing a Prefixed Canonical Authorization Domain Name. If t
I like it!

2024-02-13 15:36 UTC, slghtr-says commented on docs/BR.md
> +CAs MAY operate domains for the purpose of assisting Applicants with this validation, and MAY instruct Applicants to add a CNAME record containing a Prefixed Canonical Authorization Domain Name. If t
**Rationale**: "Control" has a specific meaning in the BRs 

> Control: “Control” (and its correlative meanings, “controlled by” and “under common control with”)
means possession, directly or indirectly, of the power to: (1) direct the management, personnel,
finances, or plans of such entity; (2) control the election of a majority of the directors ; or (3) vote
that portion of voting shares required for “control” under the law of the entity’s Jurisdiction of
Incorporation or Registration but in no case less than 10%

2024-02-13 15:47 UTC, slghtr-says commented on docs/BR.md
> +CAs MAY operate domains for the purpose of assisting Applicants with this validation, and MAY instruct Applicants to add a CNAME record containing a Prefixed Canonical Authorization Domain Name. If t
> Is it clear that this overrules the time and reuse constraints that are put on Random Value and Request Token values?

That is not included in the scope of this incremental change. While I understand the value of the Random Value and Request Token are limited in this paradigm modifying them would make this 3rd "variation" of 3.2.4.4.7 meaningfully different from the first 2 variations in practice. I want to avoid that here and push that to the follow-on discussions around a new automation based validation method.

2024-02-13 15:50 UTC, slghtr-says commented on docs/BR.md
> +  iii. restrict the DNS record types in the CA operated DNS zone to those required for confirming the Applicant’s control over the FQDN.
That is the intent but I am open for suggestions on how to make this clearer or more helpful.

2024-02-13 16:06 UTC, slghtr-says commented on docs/BR.md
> +  ii. complete the validation within the TTL of the CNAME record, or 8 hours, whichever is lesser; and
**Rationale behind the 8 hours:** The time we are measuring if from when the DNS query is performed until the results are analyzed and the domain is considered "VALID" by the DCV system. I suspect this practice typically occurs in the order of seconds or minutes under normal operating conditions. I don't suspect that CAs will have difficulty meeting an hour (in the event of a technical issue) or performing another lookup if required. That said, 8 hours is the smallest time constraint referenced in the BRs (OCSP & CAA). CAA record checks are a great parallel for this given that CAA DNS look-up have an validity floor of 8 hours. 

Since the BRs do not currently have a constraint at all on this particular practice I think staying in line with existing time constraints is reasonable. Finally, I don't suspect there is a significant increase in risk if a CA is does a DNS look-up, goes down for 6 hours and then continues the validation when the systems come back up.

2024-02-13 17:02 UTC, wthayer commented on docs/BR.md
> +
I think my confusion stems from the fact that we're using a term that begins with "prefixed" to refer to an FQDN that is not [typically] prefixed.

I'd suggest:
**Canonical Authorization Domain Name**: The domain name found within the RDATA value of a CNAME record located at an FQDN composed of an Authorization Domain Name that is prefixed with a Domain Label that begins with an underscore character.

2024-02-16 13:36 UTC, XolphinMartijn commented on docs/BR.md
> +  i. ensure that each Prefixed Canonical Authorization Domain Name is used for a unique Applicant, and not shared across multiple Applicants; and
@slghtr-says I'm not sure yet on this one. Specially when we also consider rfc8657, which is much more about account binding than applicant binding. 

I expect that for CAs, account binding is something that provides something more meaningful than applicant binding. Account binding means the CA can tie this to a specific account, and thus connected to certain credentails, whereas CAs may not have the same options for Applicants. 

If that means that we need to get Account defined, I'm all for that :) I'll give that some thought

2024-02-23 22:51 UTC, slghtr-says commented on docs/BR.md
> +  i. ensure that each Prefixed Canonical Authorization Domain Name is used for a unique Applicant, and not shared across multiple Applicants; and
Leaving this thread open for now

2024-02-23 22:51 UTC, slghtr-says commented on docs/BR.md
> +
Updated with suggested text

2024-02-23 22:52 UTC, slghtr-says commented on docs/BR.md
> +  ii. complete the validation within the TTL of the CNAME record, or 8 hours, whichever is lesser; and
Removed the TTL constraint. Will open new thread about the 8 hours.

2024-02-23 22:53 UTC, slghtr-says commented on docs/BR.md
> +  ii. complete the validation within 8 hours; and
Looking for feedback on 8 hours as a time limit. See conversation from previous iteration for more context: https://github.com/slghtr-says/servercert/pull/1#discussion_r1478572500

2024-02-23 22:58 UTC, slghtr-says commented on docs/BR.md
> +CAs MAY operate domains for the purpose of assisting Applicants with this validation, and MAY instruct Applicants to add a CNAME record containing a Canonical Authorization Domain Name controlled by
Looking for feedback on using "Applicant" rather than "Account" in this line. See prior thread for context: https://github.com/slghtr-says/servercert/pull/1#discussion_r1501247583

2024-03-06 17:24 UTC, CBonnell commented on docs/BR.md
> +  iii. restrict the DNS record types in the CA operated DNS zone to those required for confirming the Applicant’s control over the FQDN.
This might be hard to nail down into something clear. Top of mind is that this language seemingly prohibits the population of DNSSEC-specific record types, as they are not currently "required". However, I don't think such a prohibition on the use of DNSSEC is desirable.

Perhaps we can merely prohibit the inclusion of A and AAAA records?

2024-03-06 17:24 UTC, CBonnell commented on docs/BR.md
> +CAs MAY operate domains for the purpose of assisting Applicants with this validation, and MAY instruct Applicants to add a CNAME record containing a Canonical Authorization Domain Name controlled by
I prefer the use of "Applicant". The BRs should describe the goal (i.e., separation of data/validations by Applicant) as opposed to the explicit mechanism (i.e., account segregation on the CA system).

Using the term "Applicant" describes the goal, whereas "Account" describes the mechanism. Additionally, the term "Account" does not currently exist, so it would have to be created for just this case. And we would likely have to amend section 4.2.1 to use this term instead of "Applicant" when speaking to the requirements/allowances for validation data reuse.

2024-03-06 17:24 UTC, CBonnell commented on docs/BR.md
> +  ii. complete the validation within 8 hours; and
I like 8 hours as it's a sufficiently small period of time where the security goal of not relying on "old" records is achieved while providing alignment with the CAA "8-hour minimum TTL".

2024-03-08 16:14 UTC, slghtr-says commented on docs/BR.md
> +  ii. complete the validation within 8 hours; and
Thanks @CBonnell. Will resolve this thread.

2024-03-08 16:15 UTC, slghtr-says commented on docs/BR.md
> +CAs MAY operate domains for the purpose of assisting Applicants with this validation, and MAY instruct Applicants to add a CNAME record containing a Canonical Authorization Domain Name controlled by
Will keep the term "Applicant" and resolve this comment thread.

2024-04-17 20:50 UTC, merged